# Generated by Django 5.0.7 on 2024-08-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='p_email',
            field=models.EmailField(default='default_email@example.com', max_length=254),
        ),
    ]
